# configs/config.yaml

server:
  port: 8080
  debug: true

database:
  driver: postgres
  host: localhost
  port: 5432
  user: username
  password: password
  dbname: bookstore
  sslmode: disable

log:
  level: debug
