name: 1. Go Unit Test

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  load_env:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Load environment variables
      id: dotenv
      run: |
        if [ -f .env ]; then
          export $(cat .env | xargs)
        fi
        echo "NAME=${NAME}" >> $GITHUB_OUTPUT
        echo "TAGS=${TAGS}" >> $GITHUB_OUTPUT

    outputs:
      NAME: ${{ steps.dotenv.outputs.NAME }}
      TAGS: ${{ steps.dotenv.outputs.TAGS }}

  test:
    needs: load_env
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23.1'

    - name: Run unit tests
      run: ./test.sh
      shell: bash
